## -*- encoding: utf-8 -*-
## This file (notesMain_MTH3400.sagetex.sage) was *autogenerated* from notesMain_MTH3400.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('notesMain_MTH3400', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
